Feature #13: Add item search
PatLaCisay/epf-equipment-manager pull request #56
Opened 2023-05-06 18:52 UTC by e10e3

Creates a new page with a search form at `/search`. The results appear on the same page.

A drop-down menu allows to select different search criteria. The default one searches among item names and their category name.

The item display is a copy of what is on the `/item` page.

2023-05-12 07:50 UTC, PatLaCisay requested changes
C'est top pour moi bien joué. Juste une petite remarque sur le message en anglais et je merge.

PS : peux tu appeler tes branches "feat" et non "feature" j'ai galéré à faire le switch pour tester ta branche 💯

2023-05-12 07:50 UTC, PatLaCisay commented on project/templates/unified_search/index.html.twig
> +        <p>No results found for this query.</p>
On pourrait rester en français pour les messages d'erreur utilisateur

2023-05-14 14:57 UTC, e10e3 commented on project/templates/unified_search/index.html.twig
> +        <p>No results found for this query.</p>
J'ai changé le message.

2023-05-15 20:56 UTC, PatLaCisay approved these changes

2023-05-15 20:56 UTC, merged