Feat #63 : creating Faker
PatLaCisay/epf-equipment-manager pull request #64
Opened 2023-05-15 21:51 UTC by PatLaCisay

#63 Creating a faker to generate dummy data to test the app properly

2023-05-16 23:37 UTC, e10e3 requested changes
C'est une bonne idée, ça va nous être bien utile pour la suite.

2023-05-16 23:37 UTC, e10e3 commented on README.md
La partie sur la méthodologie est très complète, mais elle est peut-être un peu longue pour le Readme.
Je pense qu'il faudrait la bouger vers un fichier dédié, par exemple « CONTRIBUTING.md », et mettre un lien dans le Readme.

2023-05-16 23:37 UTC, e10e3 commented on README.md
> +Pour executer une commande de la CLI n'oubliez pas d'executer le bash du container Docker Symfony !
Coquille : `executer` → `exécuter`

2023-05-16 23:37 UTC, e10e3 commented on README.md
> +Une fois votre issue fonctionnelle en local, ou si vous voulez qu'un tiers y ait accès publiez la sur le repo distant :
Coquille : ` publiez la` → `, publiez-la`

2023-05-16 23:37 UTC, e10e3 commented on project/composer.json
> +        "fzaninotto/faker": "*",
Faker est obsolète (la bibliothèque est abandonnée). Est-ce une bonne idée de l'utiliser sur un nouveau projet ?

2023-05-16 23:37 UTC, e10e3 commented on project/migrations/Version20230515213113.php
À quoi sert cette migration ? Elle ne semble pas avoir de rapport avec le reste des changements.
Elle échoue de mon côté, il n'y a pas de champ `finalized` dans la table `borrow` de la base de données.

2023-05-16 23:37 UTC, e10e3 commented on project/src/DataFixtures/AppFixtures.php
> +            ->setCategory($entityManager->getRepository(Category::class)->find($i % sizeof($categories)-1));
Pourquoi find() est utilisé ici, et nulle part ailleurs ? Je n'ai pas de problème avec l'une ou l'autre notation, il faudrait avoir la même partout.

Cependant, il semblerait que ce find() casse la fonctionnalité des items, aucun lien n'est fait entre items et catégories (le champ catégorie est vide). Les pages `/item` et `/item/<id>` ont toutes les deux des erreurs de valeur vide (null variable).

2023-05-16 23:37 UTC, e10e3 commented on project/src/DataFixtures/AppFixtures.php
> +            ->setEndDate(DateTimeImmutable::createFromFormat($dateFormat,$faker->date($dateFormat = 'Y-m-d', $max = 'now')))
La date de fin devrait être après la date de début.

2023-05-16 23:37 UTC, e10e3 commented on project/src/DataFixtures/AppFixtures.php
> +                ->setPrice($faker->numberBetween($min = 1, $max = 200))
Il est possible de mettre un flottant ici au lieu d'un entier.

2023-05-17 10:27 UTC, PatLaCisay commented on README.md
Bonne idée

2023-05-17 10:28 UTC, PatLaCisay commented on project/composer.json
> +        "fzaninotto/faker": "*",
Oui malheureusement il n'y a pas d'alternatives

2023-05-17 10:29 UTC, PatLaCisay commented on project/migrations/Version20230515213113.php
Ca devait être un soucis local alors, je la supprime

2023-05-17 10:29 UTC, PatLaCisay commented on project/src/DataFixtures/AppFixtures.php
> +            ->setCategory($entityManager->getRepository(Category::class)->find($i % sizeof($categories)-1));
Je vais utiliser les array c'est mieux bien vu

2023-05-17 10:30 UTC, PatLaCisay commented on project/src/DataFixtures/AppFixtures.php
> +            ->setEndDate(DateTimeImmutable::createFromFormat($dateFormat,$faker->date($dateFormat = 'Y-m-d', $max = 'now')))
Oui c'est vrai je vais modifier ça ça fera des données plus cohérentes

2023-05-17 14:46 UTC, e10e3 commented on project/src/DataFixtures/AppFixtures.php
> +        $dateFormat = 'Y-m-d';
`$dateFormat` n'est pas utilisé, tu peux le supprimer.

2023-05-17 14:47 UTC, e10e3 commented on CONTRIBUTING.md
> +Pour exécuter une commande de la CLI n'oubliez pas d'executer le bash du container Docker Symfony !
Coquille : `executer` → `exécuter`

2023-05-17 14:48 UTC, e10e3 commented on CONTRIBUTING.md
> +### Créez voter branche
Coquille : `voter` → `votre`

2023-05-17 14:48 UTC, e10e3 commented on CONTRIBUTING.md
> +Ouvrez un terminal à la racine du projet "your-path/equipment-manager>" et executez les commandes suivantes :
Coquille : `executez` → `exécutez`

2023-05-18 14:56 UTC, merged