Feat #59 : user deletion with control
PatLaCisay/epf-equipment-manager pull request #72
Opened 2023-05-17 10:52 UTC by PatLaCisay

#59: users can't be deleted if their group has opened borrows or if they are admins

2023-05-22 23:22 UTC, e10e3 requested changes

2023-05-22 23:22 UTC, e10e3 commented on project/src/Controller/UserController.php
> +    #[Route('/user/delete/{id}', name: 'app_delete_user')]
Il peut être bon de limiter les identifiants admissibles à des valeurs numériques pour éviter les problèmes.

2023-05-22 23:22 UTC, e10e3 commented on project/src/Controller/UserController.php
>          }
Est-ce que ce ne serait pas un endroit où utiliser la [conversion de paramètres](https://symfony.com/doc/current/routing.html#parameter-conversion) de Symfony, au lieu de récupérer l'utilisateur manuellement ?

2023-05-22 23:22 UTC, e10e3 commented on project/src/Controller/UserController.php
> +        if($userRepo->isDeletable($user)){
Malheureusement, cette condition ne semble pas fonctionner : le bouton pour supprimer s'affiche pour l'admin et les utilisateurs avec des réservations en cours.

2023-05-22 23:22 UTC, e10e3 commented on project/src/Controller/UserController.php
> +                }
La gestion des boutons et la suppression fonctionne bien.

2023-05-22 23:22 UTC, e10e3 commented on project/src/Repository/UserRepository.php
> +
(optionnel, style) Sauter une ligne à chaque ligne fait beaucoup.

2023-05-25 12:01 UTC, PatLaCisay commented on project/src/Controller/UserController.php
> +    #[Route('/user/delete/{id}', name: 'app_delete_user')]
Qu'est ce qu tu entends par là

2023-05-25 12:02 UTC, PatLaCisay commented on project/src/Controller/UserController.php
> +        if($userRepo->isDeletable($user)){
Je vérifie

2023-05-25 12:03 UTC, PatLaCisay commented on project/src/Repository/GroupRepository.php
> +        $resultSet = $stmt->executeQuery(array('groupId'=>$group->getId()));
C'est un choix personnel je n'aime pas le DQL

2023-05-25 12:23 UTC, PatLaCisay commented on project/src/Controller/UserController.php
>          }
Oui c'est plus propre je suis pas habitué à l'utiliser

2023-05-25 21:16 UTC, e10e3 commented on project/src/Controller/UserController.php
> +    #[Route('/user/delete/{id}', name: 'app_delete_user')]
Faire correspondre la route seulement pour un identifiant numérique, pour que par exemple `/user/delete/toto` ne compte pas dedans.

Sur la doc de Symfony : https://symfony.com/doc/current/routing.html#parameters-validation

2023-06-02 14:13 UTC, merged